name: Build APK and EXE

on: workflow_dispatch

jobs:
  android:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: setup Haxe
      uses: krdlab/setup-haxe@v1.5.1
      with:
        haxe-version: '4.3.2'
    
    - name: compile
      run: |
       haxelib install hxjava
       mkdir output
       cd source
       haxe -java ../output/Main.java
    
    - name: set up dependencies
      run: haxelib install lime 8.1.0 && haxelib install openfl && lime --version
      continue-on-error: true
    
    - name: build
      run: |
       haxelib run lime setup android
       haxelib run lime config ANDROID_SETUP true
       haxelib run lime build project.xml android --app-version="4.0.0-${{ github.run_id }}" --non-interactive
    
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: bin