name: Build APK and EXE

on: workflow_dispatch

jobs:
  android:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: setup Haxe
      uses: krdlab/setup-haxe@v1.5.1
      with:
        haxe-version: 'latest'
    
    - name: compile
      run: |
       haxelib install hxjava
       mkdir output
       cd source
       haxe -java ../output/Main.java
    
    - name: set up dependencies
      run: haxelib install lime && haxelib install openfl
      continue-on-error: true
    
    - name: build
      run: |
       cd ..
       ls
       haxelib run lime setup android
       haxelib run lime build project.xml android --app-version="4.0.0-${{ github.run_id }}" --non-interactive
    
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: bin